
spring:
  datasource:
    driverclassname: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3316/local
    username: local
    password: local
    platform: mysql
    initialize: false
    maximum-pool-size: 10

server:
  port: 8081

mybatis:
  mapper-locations:
    - fr/animenfance/dao/PartenaireDao.xml
  type-aliases-package: fr.animenfance.bean

---
spring:
  profiles: container
  datasource:
    driverclassname: org.mariadb.jdbc.Driver
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    initialize: true
    maximum-pool-size: 10
